apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprodb
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      initContainers:
        - name: init-db
          image: busybox:latest
          args: ['rm', '-rf', "/var/lib/mysql/lost+found"]
          volumeMounts:
            - name: vprodbdata
              mountPath: /var/lib/mysql

      containers:
        - name: vprodb
          image: devopsaravind975/git:db
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: vprodbdata
          ports:
            - containerPort: 1433
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: db-pass
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

        - name: db-maintenance
          image: busybox:latest
          args: ['rm', '-rf', "/var/lib/mysql/lost+found"]
          volumeMounts:
            - name: vprodbdata
              mountPath: /var/lib/mysql
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"

      volumes:
        - name: vprodbdata
          persistentVolumeClaim:
            claimName: vpro-db-pvc
